additionalProperties:
  interfaceOnly: true
  useTags: true
  enumPropertyNaming: UPPERCASE
  apiPackage: com.sample.application.web.interfaces # interfaceのpackage
  modelPackage: com.sample.application.web.model # modelのpackage
