openapi: 3.0.0
info:
  title: Open API
  version: '1.0'
  description: Open all api application
  contact:
    name: contact name
servers:
  - description: Mock Server
    url: 'http://localhost:8080'
paths: {}
components:
  schemas: {}
  securitySchemes:
    ROLE_FIRST_PARTY:
      name: X-API-KEY
      type: apiKey
      in: header
tags: []
