openapi: 3.0.0
info:
  title: Dept.v1
  version: '1.0'
servers: []
paths: {}
components:
  schemas:
    Sex:
      type: string
      title: Sex
      description: ''
      enum:
        - MALE
        - FEMALE
